# Generated by Django 5.0.3 on 2025-12-13 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_blogcategory_title_en_blogcategory_title_tr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSampleConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('conversations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample_conversation', to='blog.blogs')),
            ],
        ),
    ]
