# Generated by Django 5.0.3 on 2025-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleconversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsampleconversation',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogsampleconversation',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogsampleconversation',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogsampleconversation',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
