# Generated by Django 5.0.3 on 2025-12-07 06:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custompage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='custompage',
            name='content_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='custompage',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custompage',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
