# Generated by Django 5.0.3 on 2025-12-07 06:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_alter_policy_policy_texts_alter_terms_term_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_texts_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_texts_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms',
            name='term_texts_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms',
            name='term_texts_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
