# Generated by Django 5.0.3 on 2025-11-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Workflow Page SEO',
                'verbose_name_plural': 'Workflow Page SEO',
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='Unique ID within the workflow', max_length=50)),
                ('node_type', models.CharField(choices=[('eventNode', 'Event Node'), ('agentNode', 'Agent Node'), ('connectorNode', 'Connector Node'), ('actionNode', 'Action Node'), ('logicNode', 'Logic Node')], default='connectorNode', max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('icon_slug', models.CharField(blank=True, help_text="SimpleIcons slug (e.g., 'whatsapp', 'openai', 'slack')", max_length=100, null=True)),
                ('icon_color', models.CharField(blank=True, help_text="Hex color without # (e.g., '25D366')", max_length=10, null=True)),
                ('icon_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('pos_desktop_x', models.IntegerField(default=140)),
                ('pos_desktop_y', models.IntegerField(default=140)),
                ('pos_mobile_x', models.IntegerField(default=140)),
                ('pos_mobile_y', models.IntegerField(default=140)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Node',
                'verbose_name_plural': 'Workflow Nodes',
                'ordering': ['node_id'],
                'unique_together': {('workflow', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="SimpleIcons slug (e.g., 'googlecalendar', 'slack')", max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, help_text="Hex color without # (e.g., '1A73E8')", max_length=10, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workflows.workflownode')),
            ],
            options={
                'verbose_name': 'Node Item',
                'verbose_name_plural': 'Node Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(help_text="Unique edge ID (e.g., 'e1-2')", max_length=50)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflows.workflow')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='workflows.workflownode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='workflows.workflownode')),
            ],
            options={
                'verbose_name': 'Workflow Edge',
                'verbose_name_plural': 'Workflow Edges',
                'ordering': ['edge_id'],
                'unique_together': {('workflow', 'edge_id')},
            },
        ),
    ]
