# Generated by Django 5.0.3 on 2025-12-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_templatesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfootersetting',
            name='footer_col1_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='footer_col1_description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='footer_copyright_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='footer_copyright_tr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='header_button_text_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='header_button_text_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='header_button_url_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='header_button_url_tr',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_title_tr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='seo_keywords_en',
            field=models.TextField(blank=True, default='software,application,marketer,developer', null=True),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='seo_keywords_tr',
            field=models.TextField(blank=True, default='software,application,marketer,developer', null=True),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='tag_line_en',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='tag_line_tr',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='address_en',
            field=models.CharField(blank=True, default='Your Address', max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='address_tr',
            field=models.CharField(blank=True, default='Your Address', max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='author_en',
            field=models.CharField(blank=True, default='Author Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='author_tr',
            field=models.CharField(blank=True, default='Author Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='city_en',
            field=models.CharField(blank=True, default='Your City', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='city_tr',
            field=models.CharField(blank=True, default='Your City', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='country_en',
            field=models.CharField(blank=True, default='Your Country', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='country_tr',
            field=models.CharField(blank=True, default='Your Country', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='currency_name_en',
            field=models.CharField(blank=True, default='Currency Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='currency_name_tr',
            field=models.CharField(blank=True, default='Currency Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='currency_symbol_en',
            field=models.CharField(blank=True, default='Currency Symbol', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='currency_symbol_tr',
            field=models.CharField(blank=True, default='Currency Symbol', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='name_en',
            field=models.CharField(blank=True, default='Application Name', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='name_tr',
            field=models.CharField(blank=True, default='Application Name', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='price_ragne_en',
            field=models.CharField(blank=True, default='60$ to 7000$', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='price_ragne_tr',
            field=models.CharField(blank=True, default='60$ to 7000$', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='state_en',
            field=models.CharField(blank=True, default='Your State', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='state_tr',
            field=models.CharField(blank=True, default='Your State', max_length=200, null=True),
        ),
    ]
