# Generated by Django 4.2.6 on 2025-11-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_projectsection_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidersection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Home/'),
        ),
    ]
