# Generated by Django 5.0.3 on 2025-12-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_primarymenu_url_alter_submenu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarymenu',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primarymenu',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primarymenu',
            name='url_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primarymenu',
            name='url_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='url_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='url_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
